# Generated by Django 5.0.6 on 2024-05-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpark_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='exitTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
