# Generated by Django 5.0.6 on 2024-05-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpark_app', '0002_alter_parking_exittime'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorist',
            name='account',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=9999999),
        ),
    ]
